config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resources :pages
  end
  constraints(Spree::StaticPage) do
    get '/(*path)', to: 'static_content#show', as: 'static'
  end
end

app/models/spree/page.rb
class Spree::Page < ActiveRecord::Base
  default_scope { order(position: :asc) }

  has_and_belongs_to_many :stores, join_table: 'spree_pages_stores'

  validates :title, presence: true
  validates :slug, :body, presence: true, if: :not_using_foreign_link?
  validates :layout, presence: true, if: :render_layout_as_partial?
  validates :slug, uniqueness: true, if: :not_using_foreign_link?
  validates :foreign_link, uniqueness: true, allow_blank: true

  scope :visible, -> { where(visible: true) }
  scope :header_links, -> { where(show_in_header: true).visible }
  scope :footer_links, -> { where(show_in_footer: true).visible }
  scope :sidebar_links, -> { where(show_in_sidebar: true).visible }

  scope :by_store, ->(store) { joins(:stores).where('spree_pages_stores.store_id = ?', store) }

  before_save :update_positions_and_slug

  def initialize(*args)
    super(*args)
    last_page = Spree::Page.last
    self.position = last_page ? last_page.position + 1 : 0
  end

  def link
    foreign_link.blank? ? slug : foreign_link
  end

  private

  def update_positions_and_slug
    # Ensure that all slugs start with a slash.
    slug.prepend('/') if not_using_foreign_link? && !slug.start_with?('/')
    return if new_record?
    return unless (prev_position = Spree::Page.find(id).position)
    if prev_position > position
      Spree::Page.where('? <= position and position < ?', position, prev_position).update_all('position = position + 1')
    elsif prev_position < position
      Spree::Page.where('? < position and position <= ?', prev_position, position).update_all('position = position - 1')
    end
  end

  def not_using_foreign_link?
    foreign_link.blank?
  end
end

app/controllers/spree/admin/pages_controller.rb
module Spree
  module Admin
    class PagesController < ResourceController
    end
  end
end

app/controllers/spree/static_content_controller.rb
module Spree
  class StaticContentController < StoreController
    rescue_from ActiveRecord::RecordNotFound, with: :render_404

    helper 'spree/products'
    layout :determine_layout

    def show
      @page = Spree::Page.by_store(current_store).visible.find_by_slug!(request.path)
    end

    private

    def determine_layout
      return @page.layout if @page && @page.layout.present? && !@page.render_layout_as_partial?
      Spree::Config.layout
    end

    def accurate_title
      @page ? (@page.meta_title.present? ? @page.meta_title : @page.title) : nil
    end
  end
end

app/helpers/spree/pages_helper.rb
module Spree
  module PagesHelper
    def render_snippet(slug)
      page = Spree::Page.find_by_slug(slug)
      raw page.body if page
    end
  end
end

app/views/spree/admin/pages/_form.html.erb
<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:back_to_resource_list, resource: plural_resource_name(Spree::Page)), spree.admin_pages_path, icon: 'arrow-left', class: 'btn-primary' %>
<% end %>

<%= form_for [:admin, resource] do |f| %>
  <div class="row" data-hook="admin_page_form_fields">
    <div class="col-md-6" data-hook="admin_page_form_left">
      <div class="form-group">
        <%= f.label :title %> <span class="required">*</span>
        <%= f.text_field :title, class: 'form-control' %>
        <%= f.error_message_on :title %>
      </div>

      <div class="form-group">
        <%= f.label :slug %> <span class="required">*</span>
        <%= f.text_field :slug, class: 'form-control' %>
        <%= f.error_message_on :slug %>
      </div>

      <div class="form-group">
        <%= f.label :body %> <span class="required">*</span>
        <%= f.text_area :body, rows: 12, class: 'form-control' %>
        <%= f.error_message_on :body %>
      </div>
    </div>

    <div class="col-md-6" data-hook="admin_page_form_right">
      <div class="form-group">
        <%= f.label :layout %>
        <%= f.text_field :layout, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :foreign_link %>
        <%= f.text_field :foreign_link, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :position %>
        <%= f.number_field :position, min: 0, class: 'form-control' %>
      </div>

      <div class="checkbox">
        <%= f.label :show_in_sidebar do %>
          <%= f.check_box :show_in_sidebar %>
          <%= Spree::Page.human_attribute_name(:show_in_sidebar) %>
        <% end %>
      </div>

      <div class="checkbox">
        <%= f.label :show_in_header do %>
          <%= f.check_box :show_in_header %>
          <%= Spree::Page.human_attribute_name(:show_in_header) %>
        <% end %>
      </div>

      <div class="checkbox">
        <%= f.label :show_in_footer do %>
          <%= f.check_box :show_in_footer %>
          <%= Spree::Page.human_attribute_name(:show_in_footer) %>
        <% end %>
      </div>

      <div class="checkbox">
        <%= f.label :visible do %>
          <%= f.check_box :visible %>
          <%= Spree::Page.human_attribute_name(:visible) %>
        <% end %>
      </div>

      <div class="checkbox">
        <%= f.label :render_layout_as_partial do %>
          <%= f.check_box :render_layout_as_partial %>
          <%= Spree::Page.human_attribute_name(:render_layout_as_partial) %>
        <% end %>
      </div>

      <div class="form-group">
        <%= f.label :stores, plural_resource_name(Spree::Store) %>
        <% Spree::Store.all.each do |store| %>
          <div class="checkbox">
            <%= f.label store.name.downcase.to_sym do %>
              <%= check_box_tag 'page[store_ids][]', store.id, @page.stores.include?(store) %>
              <%= store.name %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row" data-hook="admin_page_form_meta">
    <div class="col-md-12">
      <div class="form-group">
        <%= f.label :meta_title %>
        <%= f.text_field :meta_title, class: 'form-control' %>
        <%= f.error_message_on :meta_title %>
      </div>

      <div class="form-group">
        <%= f.label :meta_keywords %>
        <%= f.text_field :meta_keywords, class: 'form-control' %>
        <%= f.error_message_on :meta_keywords %>
      </div>

      <div class="form-group">
        <%= f.label :meta_description %>
        <%= f.text_field :meta_description, class: 'form-control' %>
        <%= f.error_message_on :meta_description %>
      </div>
    </div>
  </div>

  <div class="row" data-hook="admin_page_form_additional_fields">
    <div class="col-md-12"></div>
  </div>

  <%= render "spree/admin/shared/#{resource.new_record? ? 'new' : 'edit'}_resource_links" %>
<% end %>

app/views/spree/admin/pages/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:editing_resource, resource: Spree::Page.model_name.human) %>
<% end %>

<%= render 'form', resource: @page %>

app/views/spree/admin/pages/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::Page) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_page, scope: :static_content), new_object_url, icon: 'plus', class: 'btn-primary', id: 'admin_new_page' %>
<% end %>

<% if @pages.any? %>
  <table class="table" id="listing_pages" data-hook>
    <colgroup>
      <col style="width: 40%">
      <col style="width: 35%">
      <col style="width: 10%">
      <col style="width: 15%">
    </colgroup>
    <thead>
      <tr data-hook="admin_pages_index_headers">
        <th><%= Spree::Page.human_attribute_name(:title) %></th>
        <th><%= Spree.t(:link, scope: :static_content) %></th>
        <th class="text-center"><%= Spree::Page.human_attribute_name(:visible) %></th>
        <th data-hook="admin_pages_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @pages.each do |page| %>
        <tr data-hook="admin_pages_index_rows" class="<%= cycle('odd', 'even') %>" id="<%= dom_id page %>">
          <td><%= page.title %></td>
          <td><%= link_to page.link, page.link, target: '_blank' %></td>
          <td class="text-center"><%= content_tag(:i, '', class: 'icon icon-ok') if page.visible %></td>
          <td class="actions text-right" data-hook="admin_pages_index_row_actions">
            <%= link_to_edit page, no_text: true %>
            <%= link_to_delete page, no_text: true %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-warning no-objects-found">
    <%= Spree.t(:no_resource_found, resource: Spree::Page.model_name.human) %>,
    <%= link_to Spree.t(:add_one), spree.new_admin_page_path %>!
  </div>
<% end %>

app/views/spree/admin/pages/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:new_page, scope: :static_content) %>
<% end %>

<%= render 'form', resource: @page %>

app/views/spree/admin/shared/_pages_sidebar_menu.erb
<% if can? :admin, Spree::Page %>
  <ul class="nav nav-sidebar">
    <%= tab Spree::Page, url: spree.admin_pages_url, icon: 'leaf', label: plural_resource_name(Spree::Page) %>
  </ul>
<% end %>

app/views/spree/static_content/_static_content_footer.html.erb
<nav id="footer-pages">
  <ul><%= render partial: 'spree/static_content/static_content_list', collection: Spree::Page.by_store(current_store).visible.footer_links, as: :page %></ul>
</nav>

app/views/spree/static_content/_static_content_header.html.erb
<%= render partial: 'spree/static_content/static_content_list', collection: Spree::Page.by_store(current_store).visible.header_links, as: :page %>

app/views/spree/static_content/_static_content_list.html.erb
<% if page.foreign_link.present? %>
  <li><%= link_to page.title, page.foreign_link, target: '_blank', ref: 'nofollow' %></li>
<% else %>
  <% page_uri = Rails.application.routes.named_routes[:spree].path.spec.to_s == '/' ? page.slug : Rails.application.routes.named_routes[:spree].path.spec.to_s + page.slug %>
  <li class="<%= 'current' if (request.fullpath.gsub('//','/') == page_uri) %>"><%= link_to page.title, page_uri, ref: 'nofollow' %></li>
<% end %>

app/views/spree/static_content/_static_content_sidebar.html.erb
<% if Spree::Page.by_store(current_store).visible.sidebar_links.any? %>
  <nav id="pages" class="sidebar-item">
    <h4 class="pages-root filter-title">
      <%= plural_resource_name(Spree::Page) %>
    </h4>
    <ul class="pages-list list-group">
      <%= render partial: 'spree/static_content/static_content_list', collection: Spree::Page.visible.sidebar_links, as: :page %>
    </ul>
  </nav>
<% end %>

app/views/spree/static_content/show.html.erb
<% if @page.layout.present? and @page.render_layout_as_partial? %>
  <%= render partial: @page.layout %>
<% else %>
  <% content_for :head do -%>
    <%- if @page.meta_title.present? -%>
      <meta name="title" content="<%= @page.meta_title %>">
    <%- else -%>
      <meta name="title" content="<%= @page.title %>">
    <%- end -%>
    <meta name="keywords" content="<%= @page.meta_keywords %>">
    <meta name="description" content="<%= @page.meta_description %>">
  <% end -%>

  <% content_for :sidebar do %>
    <% if (defined? @products) && (defined? @taxon) %>
      <%= render partial: 'spree/shared/filters' %>
    <% elsif defined? @taxonomies %>
      <%= render partial: 'spree/shared/taxonomies' %>
    <% end %>
  <% end %>

  <h1><%= @page.title %></h1>
  <div id="page_content">
    <%= raw @page.body %>
  </div>
<% end %>